version: '3'
services:
  web:
    image: web-apache
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html
    networks:
      - webnet
networks:
  webnet: